services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: prd-kamui-backend
    env_file: .env.prd
    ports:
      - "3000:3000"
    depends_on:
      mariadb:
        condition: service_started
    networks:
      - kamui-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
      args: 
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: prd-kamui-frontend
    ports:
      - "81:80"
    depends_on:
      - backend
    networks:
      - kamui-network

  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    env_file: .env.prd
    ports:
      - "3306:3306"
    volumes:
      - prd_mariadb_data:/var/lib/mysql
    networks:
      - kamui-network

networks:
  kamui-network:
    driver: bridge

volumes:
  prd_mariadb_data:
